#!/bin/bash

#-----------------------------------------------------------------------------
# Configure the service:
#-----------------------------------------------------------------------------

: ${ETCD_PATH:=/mongo}
: ${ETCD_ENDPOINT:=http://127.0.0.1:2379}
: ${ETCD_BOOT:=false}

#-----------------------------------------------------------------------------
# Functions:
#-----------------------------------------------------------------------------

function token() {

  local ETCDCTL="etcdctl --endpoint ${ETCD_ENDPOINT}"

  while true; do

    TKN=$(${ETCDCTL} get ${ETCD_PATH}/token 2>/dev/null); [ "$?" -eq 4 ] && {
    ${ETCDCTL} mk ${ETCD_PATH}/token '0' &>/dev/null || { sleep 1; continue; }
    } || { [ "${TKN}" != 0 ] && return 1; }

    ${ETCDCTL} set --swap-with-value '0' ${ETCD_PATH}/token '1' &>/dev/null \
    && return 0; sleep 1

  done
}

#-----------------------------------------------------------------------------
# Get the bootstrap token:
#-----------------------------------------------------------------------------

MSG1="[Populate etcd] Attempting to acquire the bootstrap token..."
MSG2="[Populate etcd] Ok! Token acquired"
MSG3="[Populate etcd] Someone else owns the token"

[ "${ETCD_BOOT}" == "true" ] && {
  echo ${MSG1} && token && {
    echo ${MSG2}
  } || echo ${MSG3}
}

#-----------------------------------------------------------------------------
# Run:
#-----------------------------------------------------------------------------

exec mongod "$@"
